#!/usr/bin/env python3

import os
import subprocess

#각각 중요 파일의 수정된 정보 수집

logdir="/var/log" #기본 로그 파일
pwddir="/etc/passwd" # 암호화된 파일
netdir="/etc/sysconfig" #네트워크 설정 파일
memdir="/proc/meminfo" # 메모리 관련 정보 파일

def important_file_info(): 

	try: 

	print(“----------Log File Information----------”)

	subprocess.run(‘find $logdir -name "*.log" -mtime –3 –print’ >> ‘logfile_info.txt’, shell=True) # 3일 전까지 갱신된 파일 출력
	subprocess.run(‘find $logdir -mmin -30 -type f –ls’ >> ‘logfile_info.txt’, shell=True) # 30분 이내의 수정한 파일 출력

	subprocess.run(‘find $pwddir –type f -mtime –3 –print’ >> ‘logfile_info.txt’, shell=True) 
	subprocess.run(‘find $pwddir -mmin -30 -type f –ls’ >> ‘logfile_info.txt’, shell=True) 

	subprocess.run(‘find $netdir –type f -mtime –3 –print’ >> ‘logfile_info.txt’, shell=True) 
	subprocess.run(‘find $netdir -mmin -30 -type f –ls’ >> ‘logfile_info.txt’, shell=True) 

	subprocess.run(‘find $memdir –type f -mtime –3 –print’ >> ‘logfile_info.txt’, shell=True) 
	subprocess.run(‘find $memdir -mmin -30 -type f –ls’ >> ‘logfile_info.txt’, shell=True) 

	except Exception as e:
	print(“----------Error----------”)
