#!/usr/bin/python3

import os

# 해당 디렉터리 밑 숨겨진 파일 
# 리눅스 중요 파일 정보만 수집

def HdFile():
	os.system('ls -l /etc' > a1.txt)  
	os.system('ls -l /proc' > a1.txt)
	os.system('ls -l /var' > a1.txt) 


HdFile()


# 생성 또는 변경된 파일 

def CgFile():
	os.system('find /bin –type f -mtime -30' > b1.txt)
	os.system('find /bin –type f –ctime -7' > b1.txt) 
	os.system('ind /bin –type f –atime -7' > b1.txt)

CgFile()


# 특수 권한을 가진 파일

def AtFile():

	os.sytem('find / -uid 0 –perm 4000' > c.txt)

AtFile()


# 코드 안돌아감
# NameError 계속 뜸
